# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update Empirical Bayes Estimates for Stage 1 & 2
#'
#' Calculates the updated Empirical Bayes (EB) estimates for the random effects
#' means (theta) and standard deviations (psd) using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param eb_prev_theta Vector of previous iteration's EB mean estimates.
#' @param eb_prev_psd Vector of previous iteration's EB standard deviation estimates.
#'
#' @return A list containing:
#' \item{eb_theta}{Updated vector of random effect means.}
#' \item{eb_psd}{Updated vector of random effect standard deviations.}
#' @keywords internal
update_eb_estimates_rcpp <- function(params, X, U, Z, y, id, points, weights, eb_prev_theta, eb_prev_psd) {
    .Call(`_MixLS_update_eb_estimates_rcpp`, params, X, U, Z, y, id, points, weights, eb_prev_theta, eb_prev_psd)
}

#' Update Bivariate Empirical Bayes Estimates for Stage 3
#'
#' Updates the bivariate EB estimates for the mixed effects location-scale model.
#' Handles independent, linear, interaction, and quadratic model types.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_prev_theta2 Matrix (n x 2) of previous EB mean estimates.
#' @param eb_prev_thetav Matrix (n x 3) of previous EB variance-covariance estimates (var1, cov, var2).
#'
#' @return A list containing:
#' \item{theta2_eb}{Updated matrix (n x 2) of random effect means.}
#' \item{thetav_eb}{Updated matrix (n x 3) of variances and covariance.}
#' @keywords internal
update_eb_estimates_stage3_rcpp <- function(params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_prev_theta2, eb_prev_thetav) {
    .Call(`_MixLS_update_eb_estimates_stage3_rcpp`, params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_prev_theta2, eb_prev_thetav)
}

#' Calculate gradient for Stage 1 & 2 log-likelihood (Fixed Quadrature)
#'
#' Computes the gradient of the log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#'
#' @return A vector containing the gradient of the log-likelihood.
#' @keywords internal
stage12_gradient_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_gradient_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate gradient for Stage 1 & 2 log-likelihood (Adaptive Quadrature)
#'
#' Computes the gradient of the log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta Vector of Empirical Bayes estimates for random effect means.
#' @param eb_sd Vector of Empirical Bayes estimates for random effect standard deviations.
#'
#' @return A vector containing the gradient of the log-likelihood.
#' @keywords internal
stage12_gradient_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd) {
    .Call(`_MixLS_stage12_gradient_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd)
}

#' Calculate gradient for Stage 3 (Fixed Quadrature)
#'
#' Computes the gradient of the log-likelihood for the Stage 3 model (bivariate random effects)
#' using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#'
#' @return A vector containing the gradient of the log-likelihood.
#' @keywords internal
stage3_gradient_combined <- function(params, X, U, Z, y, id, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_gradient_combined`, params, X, U, Z, y, id, points, weights, model_type)
}

#' Calculate gradient for Stage 3 (Adaptive Quadrature)
#'
#' Computes the gradient of the log-likelihood for the Stage 3 model (bivariate random effects)
#' using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta2 Matrix (n x 2) of Empirical Bayes estimates for random effect means.
#' @param eb_thetav Matrix (n x 3) of Empirical Bayes estimates for random effect variances/covariances.
#'
#' @return A vector containing the gradient of the log-likelihood.
#' @keywords internal
stage3_gradient_adaptive_combined <- function(params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_gradient_adaptive_combined`, params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Calculate Hessian matrix for Stage 1 & 2 log-likelihood (Fixed Quadrature)
#'
#' Computes the Hessian of the log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#'
#' @return The Hessian matrix of dimension (n_params x n_params).
#' @keywords internal
stage12_hessian_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_hessian_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate Hessian matrix for Stage 1 & 2 log-likelihood (Adaptive Quadrature)
#'
#' Computes the Hessian of the log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta Vector of Empirical Bayes estimates for random effect means.
#' @param eb_sd Vector of Empirical Bayes estimates for random effect standard deviations.
#'
#' @return The Hessian matrix of dimension (n_params x n_params).
#' @keywords internal
stage12_hessian_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd) {
    .Call(`_MixLS_stage12_hessian_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd)
}

#' Calculate Hessian matrix for Stage 3 (Fixed Quadrature)
#'
#' Computes the Hessian of the log-likelihood for the Stage 3 model (bivariate random effects)
#' using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#'
#' @return The Hessian matrix of dimension (n_params x n_params).
#' @keywords internal
stage3_hessian_combined <- function(params, X, U, Z, y, id, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_hessian_combined`, params, X, U, Z, y, id, points, weights, model_type)
}

#' Calculate Hessian matrix for Stage 3 (Adaptive Quadrature)
#'
#' Computes the Hessian of the log-likelihood for the Stage 3 model (bivariate random effects)
#' using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta2 Matrix (n x 2) of Empirical Bayes estimates for random effect means.
#' @param eb_thetav Matrix (n x 3) of Empirical Bayes estimates for random effect variances/covariances.
#'
#' @return The Hessian matrix of dimension (n_params x n_params).
#' @keywords internal
stage3_hessian_adaptive_combined <- function(params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_hessian_adaptive_combined`, params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Calculate log-likelihood for Stage 1 & 2 (Fixed Quadrature)
#'
#' Computes the marginal log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#'
#' @return The total log-likelihood (scalar double).
#' @keywords internal
stage12_loglik_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_loglik_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate log-likelihood for Stage 1 & 2 (Adaptive Quadrature)
#'
#' Computes the marginal log-likelihood for the mixed effects location-scale model
#' (Stage 1 & 2) using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta Vector of Empirical Bayes estimates for random effect means.
#' @param eb_sd Vector of Empirical Bayes estimates for random effect standard deviations.
#'
#' @return The total log-likelihood (scalar double).
#' @keywords internal
stage12_loglik_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd) {
    .Call(`_MixLS_stage12_loglik_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, eb_theta, eb_sd)
}

#' Calculate log-likelihood for Stage 3 (Fixed Quadrature)
#'
#' Computes the marginal log-likelihood for the Stage 3 model (bivariate random effects)
#' using standard Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#'
#' @return The total log-likelihood (scalar double).
#' @keywords internal
stage3_loglik_combined <- function(params, X, U, Z, y, id, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_loglik_combined`, params, X, U, Z, y, id, points, weights, model_type)
}

#' Calculate log-likelihood for Stage 3 (Adaptive Quadrature)
#'
#' Computes the marginal log-likelihood for the Stage 3 model (bivariate random effects)
#' using adaptive Gaussian quadrature.
#'
#' @param params A vector of model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y The response vector.
#' @param id A vector of subject IDs.
#' @param points Vector of standard Quadrature points.
#' @param weights Vector of standard Quadrature weights.
#' @param model_type String specifying the model type ("independent", "linear", "quadratic" and "interaction").
#' @param adaptive Integer flag (0 or 1) indicating if adaptive quadrature is used.
#' @param eb_theta2 Matrix (n x 2) of Empirical Bayes estimates for random effect means.
#' @param eb_thetav Matrix (n x 3) of Empirical Bayes estimates for random effect variances/covariances.
#'
#' @return The total log-likelihood (scalar double).
#' @keywords internal
stage3_loglik_adaptive_combined <- function(params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_loglik_adaptive_combined`, params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Solve linear system using appropriate numerical method
#' 
#' Attempts to solve Ax=b using Cholesky decomposition first,
#' falls back to QR decomposition if Cholesky fails
#'
#' @param hess_adj The adjusted Hessian matrix
#' @param grad The gradient vector
#' @return Solution vector, or empty vector if solving fails
solve_matrix_rcpp <- function(hess_adj, grad) {
    .Call(`_MixLS_solve_matrix_rcpp`, hess_adj, grad)
}

