# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update Empirical Bayes Estimates for Stage 1 & 2
#'
#' This function calculates the posterior mean and standard deviation for the random
#' intercept in the Stage 1 & 2 models. It uses the parameter estimates from the
#' current iteration to perform numerical integration via Gaussian quadrature for
#' each subject. The calculation is parallelized across subjects using OpenMP.
#'
#' @param params Vector of current model parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Response vector.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param eb_prev_theta EB mean estimates from the previous iteration.
#' @param eb_prev_psd EB standard deviation estimates from the previous iteration.
#' @return A Rcpp::List containing two named elements: `theta_eb` (a vector of the
#'   updated posterior means) and `psd_eb` (a vector of the updated posterior
#'   standard deviations).
update_eb_estimates_rcpp <- function(params, X, U, Z, y, id, points, weights, eb_prev_theta, eb_prev_psd) {
    .Call(`_MixLS_update_eb_estimates_rcpp`, params, X, U, Z, y, id, points, weights, eb_prev_theta, eb_prev_psd)
}

#' Update Bivariate Empirical Bayes Estimates for Stage 3
#'
#' This function calculates the posterior mean vector (2x1) and variance-covariance matrix
#' (2x2) for the bivariate random effects (location and scale) in the Stage 3 model.
#' It uses 2D numerical integration and is parallelized across subjects.
#'
#' @param params Vector of current model parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Response vector.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type A string specifying the Stage 3 model type ("linear", "quadratic", etc.).
#' @param adaptive An integer flag (1 for adaptive quadrature, 0 for fixed).
#' @param eb_prev_theta2 A matrix (n_subjects x 2) of the posterior means from the previous iteration.
#' @param eb_prev_thetav A matrix (n_subjects x 3) of the unique posterior
#'   variance-covariance elements [Var1, Cov, Var2] from the previous iteration.
#' @return A Rcpp::List containing two named elements: `theta2_eb` (a matrix of the
#'   updated posterior means) and `thetav_eb` (a matrix of the updated posterior
#'   variance-covariance elements).
update_eb_estimates_stage3_rcpp <- function(params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_prev_theta2, eb_prev_thetav) {
    .Call(`_MixLS_update_eb_estimates_stage3_rcpp`, params, X, U, Z, y, id, points, weights, model_type, adaptive, eb_prev_theta2, eb_prev_thetav)
}

#' Calculate gradient for Stage 1 & 2 log-likelihood
#'
#' This function computes the gradient of the log-likelihood for the Stage 1 & 2
#' models using fixed Gaussian-Hermite quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @return A vector containing the gradient of the log-likelihood.
stage12_gradient_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_gradient_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate gradient for Stage 1 & 2 with adaptive quadrature
#'
#' This function computes the gradient using adaptive Gaussian-Hermite quadrature,
#' where the integration grid is centered and scaled based on Empirical Bayes
#' estimates from the previous iteration.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param theta_eb Vector of EB posterior means for each subject.
#' @param psd_eb Vector of EB posterior standard deviations for each subject.
#' @return A vector containing the gradient of the log-likelihood.
stage12_gradient_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb) {
    .Call(`_MixLS_stage12_gradient_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb)
}

#' Calculate gradient for Stage 3 mixed-effects location-scale model
#'
#' This function computes the gradient for the Stage 3 model, which includes
#' bivariate random effects for location and scale. It uses 2D numerical
#' integration and is parallelized across subjects.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type A string specifying the Stage 3 model type ("linear", etc.).
#' @return A vector containing the gradient of the log-likelihood.
stage3_gradient_combined <- function(params, X, U, Z, y, id, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_gradient_combined`, params, X, U, Z, y, id, points, weights, model_type)
}

#' Calculate gradient for Stage 3 with adaptive quadrature
#'
#' This function computes the gradient for the Stage 3 model using 2D adaptive
#' Gaussian-Hermite quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id_numeric Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type A string specifying the Stage 3 model type.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param eb_theta2 Matrix (n_subjects x 2) of EB posterior means.
#' @param eb_thetav Matrix (n_subjects x 3) of EB posterior VCV elements.
#' @return A vector containing the gradient of the log-likelihood.
stage3_gradient_adaptive_combined <- function(params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_gradient_adaptive_combined`, params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Calculate Hessian matrix for Stage 1 & 2 log-likelihood (C++)
#'
#' This function computes the Hessian matrix (second derivatives) of the
#' log-likelihood for the Stage 1 & 2 models using fixed Gaussian-Hermite quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @return The Hessian matrix of the log-likelihood.
stage12_hessian_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_hessian_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate Hessian for Stage 1 & 2 with adaptive quadrature
#'
#' Computes the Hessian matrix using adaptive Gaussian-Hermite quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param theta_eb Vector of EB posterior means for each subject.
#' @param psd_eb Vector of EB posterior standard deviations for each subject.
#' @return The Hessian matrix of the log-likelihood.
stage12_hessian_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb) {
    .Call(`_MixLS_stage12_hessian_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb)
}

#' Calculate Hessian matrix for Stage 3 model
#'
#' Computes the Hessian matrix for the Stage 3 model using 2D fixed quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type String specifying the Stage 3 model type.
#' @return The Hessian matrix of the log-likelihood.
stage3_hessian_combined <- function(params, X, U, Z, y, id, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_hessian_combined`, params, X, U, Z, y, id, points, weights, model_type)
}

#' Calculate Hessian for Stage 3 with adaptive quadrature
#'
#' Computes the Hessian matrix for the Stage 3 model using 2D adaptive quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id_numeric Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type String specifying the Stage 3 model type.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param eb_theta2 Matrix (n_subjects x 2) of EB posterior means.
#' @param eb_thetav Matrix (n_subjects x 3) of EB posterior VCV elements.
#' @return The Hessian matrix of the log-likelihood.
stage3_hessian_adaptive_combined <- function(params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_hessian_adaptive_combined`, params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Calculate log-likelihood for Stage 1 & 2
#'
#' Computes the log-likelihood for the Stage 1 & 2 models using fixed
#' Gaussian-Hermite quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @return The total log-likelihood value for all subjects.
stage12_loglik_rcpp <- function(params, X, U, Z, y, id, points, weights) {
    .Call(`_MixLS_stage12_loglik_rcpp`, params, X, U, Z, y, id, points, weights)
}

#' Calculate log-likelihood for Stage 1 & 2 with adaptive quadrature
#'
#' Computes the log-likelihood using adaptive Gaussian-Hermite quadrature, where
#' the integration grid is centered and scaled based on Empirical Bayes estimates.
#'
#' @param params Vector of parameters (beta, alpha, tau).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param theta_eb Vector of EB posterior means for each subject.
#' @param psd_eb Vector of EB posterior standard deviations for each subject.
#' @return The total log-likelihood value for all subjects.
stage12_loglik_adaptive <- function(params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb) {
    .Call(`_MixLS_stage12_loglik_adaptive`, params, X, U, Z, y, id, points, weights, adaptive, theta_eb, psd_eb)
}

#' Calculate log-likelihood for stage 3 mixed-effects location scale model
#'
#' Computes the log-likelihood for the stage 3 model using 2D fixed quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id_numeric Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type String specifying the Stage 3 model type.
#' @return The total log-likelihood value.
stage3_loglik_combined <- function(params, X, U, Z, y, id_numeric, points, weights, model_type = "linear") {
    .Call(`_MixLS_stage3_loglik_combined`, params, X, U, Z, y, id_numeric, points, weights, model_type)
}

#' Calculate log-likelihood for Stage 3 with adaptive quadrature
#'
#' Computes the log-likelihood for the Stage 3 model using 2D adaptive quadrature.
#'
#' @param params Vector of parameters (beta, alpha, tau, sigma).
#' @param X Design matrix for fixed effects.
#' @param U Design matrix for between-subject variance.
#' @param Z Design matrix for within-subject variance.
#' @param y Vector of response values.
#' @param id_numeric Vector of subject identifiers (0-based).
#' @param points Standard Gaussian-Hermite quadrature points.
#' @param weights Standard Gaussian-Hermite quadrature weights.
#' @param model_type String specifying the Stage 3 model type.
#' @param adaptive Integer flag (1 for adaptive, 0 for fixed).
#' @param eb_theta2 Matrix (n_subjects x 2) of EB posterior means.
#' @param eb_thetav Matrix (n_subjects x 3) of EB posterior VCV elements.
#' @return The total log-likelihood value.
stage3_loglik_adaptive_combined <- function(params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav) {
    .Call(`_MixLS_stage3_loglik_adaptive_combined`, params, X, U, Z, y, id_numeric, points, weights, model_type, adaptive, eb_theta2, eb_thetav)
}

#' Solve linear system using appropriate numerical method
#' 
#' Attempts to solve Ax=b using Cholesky decomposition first,
#' falls back to QR decomposition if Cholesky fails
#'
#' @param hess_adj The adjusted Hessian matrix
#' @param grad The gradient vector
#' @return Solution vector, or empty vector if solving fails
solve_matrix_rcpp <- function(hess_adj, grad) {
    .Call(`_MixLS_solve_matrix_rcpp`, hess_adj, grad)
}

